### ISSUE TITLE
get-pipsi ignores piped python

### ISSUE THREAD

**Issue by pikeas** [mitsuhiko/pipsi#88]
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python3
    Installing pipsi
    New python executable in /Users/apikeas/.local/venvs/pipsi/bin/python2.7

Expected: python executable should be python3.x.

**Comment by RonnyPfannschmidt** [comment]
@pikeas pipsi indeed does ignore the python that is used and just invokes virtualenv

for pipsi itself that is not a problem at all since it really does not matter what python version you use for pipsi

now the main question is if/how you want to set the default python for pipsi, but i think thats a matter for a different issue

im inclined to consider the current behavior surprising, but not wrong, but im happy to revisit that oppinion

**Comment by nnutter** [comment]
The solution to this should probably take into account the fact that for some arbitrary `pipsi install` it may be necessary to use either Python 2 or Python 3.

**Comment by williamsmj** [comment]
Am I right in thinking that it does matter which python version you use for pipsi, since that version will be the default for things you `pipsi install` without the `--python` option?

In that sense, it would be useful for the installer to use exactly the interpreter it was piped into, since it would above the confusion of this issue, and also allow an easy way to control which version pipsi uses (simply pipe it to a different `python`).

I see two ways to do this. The more proper (but more work) would be to refactor `get-pipsi.py` to `import virtualenv` and use the virtualenv module to create the environments within python, rather fragile shell calls.

Alternatively, a simpler but less "correct" solution would be to
 - figure out the path to the python interpreter the installer script was piped into using `sys.executable`
 - issue the command `sys.executable + " -m virtualenv"`, rather than `virtualenv` directly. 

Either would guarantee that pipsi is installed with the python version that the installer script was piped to, which is not an unreasonable expectation IMO.

I don't have time to do the first option, but I'd be glad to submit a PR for the second if it would be useful? Let me know.

**Comment by mmerickel** [comment]
Please see https://github.com/mitsuhiko/pipsi/pull/91. There's no real reason this hasn't been merged. I even offered to help with maintenance which has fallen of deaf ears.

**Comment by RonnyPfannschmidt** [comment]
#91 got merged nw
